name: CI

on:
  push:
    branches: '*'
  pull_request:
    branches: '*'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x, 16.x, 18.x]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up JDK 17 ${{ matrix.node-version }}
        uses: actions/setup-java@v1
        with:
          java-version: 17 
          node-version: ${{ matrix.node-version }}
      - name: Build
        run: |
          chmod +x ./gradlew
          ./gradlew build

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: app-debug.apk
          path: app/build/outputs/apk/debug/app-debug.apk
